-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Create Tables

-- Vehicles table
CREATE TABLE IF NOT EXISTS vehicles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    vehicle_type VARCHAR(20) NOT NULL CHECK (vehicle_type IN ('R4', 'R2', 'R2_KECIL')),
    license_plate VARCHAR(20) UNIQUE NOT NULL,
    chassis_number VARCHAR(50),
    engine_number VARCHAR(50),
    body_number VARCHAR(50),
    brand_type VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Goods/Items table
CREATE TABLE IF NOT EXISTS goods (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    item_code VARCHAR(50) UNIQUE NOT NULL, -- Will be generated by trigger/function or frontend
    name VARCHAR(200) NOT NULL,
    unit VARCHAR(50) NOT NULL,
    item_type VARCHAR(20) NOT NULL CHECK (item_type IN ('PERSEDIAAN', 'NON_PERSEDIAAN')),
    current_stock INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Suppliers table
CREATE TABLE IF NOT EXISTS suppliers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(200) NOT NULL,
    pic_name VARCHAR(100),
    phone_number VARCHAR(20),
    address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Mechanics table
CREATE TABLE IF NOT EXISTS mechanics (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(100) NOT NULL,
    specialization VARCHAR(20) NOT NULL CHECK (specialization IN ('R4', 'R2', 'R2_KECIL', 'R4_R2', 'ALL')),
    phone_number VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Job Types table (Missing in original DDL but needed for 'Menu Pekerjaan')
CREATE TABLE IF NOT EXISTS job_types (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    job_name VARCHAR(200) NOT NULL,
    job_group VARCHAR(50) NOT NULL CHECK (job_group IN ('PERBAIKAN', 'SERVICE_RINGAN')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Budget periods table
CREATE TABLE IF NOT EXISTS budget_periods (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    month VARCHAR(20) NOT NULL,
    year INTEGER NOT NULL,
    UNIQUE(month, year),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Budget Allocations (Detail for Budget Periods)
CREATE TABLE IF NOT EXISTS budget_allocations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    period_id UUID REFERENCES budget_periods(id) ON DELETE CASCADE,
    vehicle_type VARCHAR(20) CHECK (vehicle_type IN ('R4', 'R2', 'R2_KECIL')),
    service_group VARCHAR(50) CHECK (service_group IN ('PERBAIKAN', 'SERVICE_RINGAN')),
    amount DECIMAL(15,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Vehicle entries table
CREATE TABLE IF NOT EXISTS vehicle_entries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    entry_number VARCHAR(50) UNIQUE NOT NULL, -- Auto generated
    vehicle_id UUID REFERENCES vehicles(id),
    entry_date DATE NOT NULL,
    estimated_finish_date DATE,
    reference_number VARCHAR(50), -- No. Ref/Record
    nota_dinas_number VARCHAR(50), -- No. Nota Dinas
    service_group VARCHAR(50) NOT NULL CHECK (service_group IN ('PERBAIKAN', 'SERVICE_RINGAN')),
    notes TEXT,
    status VARCHAR(20) DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'PROCESSED', 'CLOSED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Vehicle Entry Jobs (Many-to-Many between Entry and Job Types)
CREATE TABLE IF NOT EXISTS vehicle_entry_jobs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    vehicle_entry_id UUID REFERENCES vehicle_entries(id) ON DELETE CASCADE,
    job_type_id UUID REFERENCES job_types(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Work orders table
CREATE TABLE IF NOT EXISTS work_orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    wo_number VARCHAR(50) UNIQUE NOT NULL,
    vehicle_entry_id UUID REFERENCES vehicle_entries(id),
    mechanic_id UUID REFERENCES mechanics(id),
    work_date DATE NOT NULL,
    status VARCHAR(30) DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CLOSED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Purchase orders table
CREATE TABLE IF NOT EXISTS purchase_orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    po_number VARCHAR(50) UNIQUE NOT NULL,
    supplier_id UUID REFERENCES suppliers(id),
    work_order_id UUID REFERENCES work_orders(id), -- Optional link to WO
    status VARCHAR(30) DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'ISSUED', 'RECEIVED_PART', 'RECEIVED_FULL')),
    total_amount DECIMAL(15,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Purchase Order Items
CREATE TABLE IF NOT EXISTS purchase_order_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    po_id UUID REFERENCES purchase_orders(id) ON DELETE CASCADE,
    goods_id UUID REFERENCES goods(id),
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(15,2),
    total_price DECIMAL(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Goods Receipts (Penerimaan Barang)
CREATE TABLE IF NOT EXISTS goods_receipts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    receipt_number VARCHAR(50) UNIQUE NOT NULL,
    po_id UUID REFERENCES purchase_orders(id),
    receipt_date DATE NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS purchase_returns (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    return_number VARCHAR(50) UNIQUE NOT NULL,
    po_id UUID REFERENCES purchase_orders(id),
    return_date DATE NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS purchase_return_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    return_id UUID REFERENCES purchase_returns(id) ON DELETE CASCADE,
    goods_id UUID REFERENCES goods(id),
    quantity_returned NUMERIC NOT NULL DEFAULT 0,
    unit_price NUMERIC NOT NULL DEFAULT 0,
    total_price NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Goods Issues (Barang Keluar)
CREATE TABLE IF NOT EXISTS goods_issues (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    issue_number VARCHAR(50) UNIQUE NOT NULL,
    work_order_id UUID REFERENCES work_orders(id),
    issue_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Goods Issue Items
CREATE TABLE IF NOT EXISTS goods_issue_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    issue_id UUID REFERENCES goods_issues(id) ON DELETE CASCADE,
    goods_id UUID REFERENCES goods(id),
    quantity INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- 2. Enable Row Level Security (RLS)
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE goods ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE mechanics ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE budget_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE budget_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle_entry_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE goods_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE goods_issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE goods_issue_items ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies (Open for now for simplicity, but authenticated)
-- Allow all authenticated users to do everything (adjust as needed for roles)
CREATE POLICY "Enable all access for authenticated users" ON vehicles FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for authenticated users" ON goods FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for authenticated users" ON suppliers FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for authenticated users" ON mechanics FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for authenticated users" ON job_types FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for authenticated users" ON budget_periods FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for authenticated users" ON budget_allocations FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for authenticated users" ON vehicle_entries FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for authenticated users" ON vehicle_entry_jobs FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for authenticated users" ON work_orders FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for authenticated users" ON purchase_orders FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for authenticated users" ON purchase_order_items FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for authenticated users" ON goods_receipts FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for authenticated users" ON goods_issues FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for authenticated users" ON goods_issue_items FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Allow public read access (optional, remove if strict security needed)
CREATE POLICY "Enable read access for anon" ON vehicles FOR SELECT TO anon USING (true);
CREATE POLICY "Enable read access for anon" ON goods FOR SELECT TO anon USING (true);
CREATE POLICY "Enable read access for anon" ON suppliers FOR SELECT TO anon USING (true);
CREATE POLICY "Enable read access for anon" ON mechanics FOR SELECT TO anon USING (true);
CREATE POLICY "Enable read access for anon" ON job_types FOR SELECT TO anon USING (true);


-- 4. Sequences for Auto-generating Numbers (Simulated with Functions)
-- Function to generate next number
CREATE OR REPLACE FUNCTION generate_entry_number() RETURNS TRIGGER AS $$
BEGIN
  NEW.entry_number := 'ENT-' || TO_CHAR(NOW(), 'YYYYMMDD') || '-' || substring(md5(random()::text) from 1 for 4);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_entry_number
BEFORE INSERT ON vehicle_entries
FOR EACH ROW
WHEN (NEW.entry_number IS NULL)
EXECUTE FUNCTION generate_entry_number();

-- Function for Item Code
CREATE OR REPLACE FUNCTION generate_item_code() RETURNS TRIGGER AS $$
BEGIN
  NEW.item_code := 'BRG-' || substring(md5(random()::text) from 1 for 6);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_item_code
BEFORE INSERT ON goods
FOR EACH ROW
WHEN (NEW.item_code IS NULL)
EXECUTE FUNCTION generate_item_code();

